### ISSUE TITLE
Support Rails 5?

### ISSUE THREAD

**Issue by radicaled** [SchemaPlus/schema_plus_pg_indexes#10]
ActiveRecord support seems to be pinned to 4.x

**Comment by ronen** [comment]
Yeah.  First step would be supporting Rails 5 in schema_plus_core.  See SchemaPlus/schema_plus_core#9

**Comment by rhymes** [comment]
Any updates on this?

I saw this ticket https://github.com/SchemaPlus/schema_plus/issues/229

**Comment by boazy** [comment]
@rhymes: @myabc has a pill request for that but I'm not sure if it's ready. I'll take a look at that at my next opportunity.

**Comment by rhymes** [comment]
@boazy thank you!

**Comment by boazy** [comment]
@rhymes Please see #13

**Comment by boazy** [comment]
Rails 5.0.1 support is now in. Closing issue.
