### ISSUE TITLE
Please upgrade gem for Rails 5.1.0

### ISSUE THREAD

**Issue by jasnow** [SchemaPlus/schema_plus_pg_indexes#15]
Getting
```
    schema_plus_pg_indexes was resolved to 0.1.0, which depends on
      activerecord (~> 4.2)
```
for Rails 5.1 and Ruby 2.4.1 on Mac 10.12.4.

**Comment by elsurudo** [comment]
@jasnow For now, feel free to use my fork that relaxes the requirements:

In your gemfile:
```
gem 'schema_plus_pg_indexes'
gem 'schema_plus_indexes', git: 'https://github.com/elsurudo/schema_plus_indexes.git', branch: 'rails-5.1'
```

I haven't tested it much yet – will report any issues I come across.

**Comment by jasnow** [comment]
Above workaround allow me to upgrade from Rails 5.1.0.rc2 to 5.1.0.

**Comment by elsurudo** [comment]
Just note that there's probably a reason that the requirements are strict – the implementation of these gems is tied pretty closely to the activerecord API, so if that changes, things may break in subtle ways. So testing is important.

**Comment by iagopiimenta** [comment]
Any progress with this?

**Comment by ronen** [comment]
> Any progress with this?

Not much.  schema_plus_core needs some (hopefully minor) work to conform to 5.1 then the other gems can build off that, hopefully without too much work.   Really hoping that somebody will motivate to dive in as I myself don't have time right now.  See SchemaPlus/schema_plus_core#19

**Comment by ronen** [comment]
Thanks to @iagopiimenta, schema_plus_core has been updated.  Then it was a quick matter for me to update this gem.  Version 0.3.0 is released now.

**Comment by jasnow** [comment]
Verified - Thanks

**Comment by ronen** [comment]
@jasnow thanks for confirming

**Comment by jasnow** [comment]
Always glad to help
