### ISSUE TITLE
This gem is unnecessary - Add rails 5 warning or remove support

### ISSUE THREAD

**Issue by iagopiimenta** [SchemaPlus/schema_plus_pg_indexes#16]
Rails 5 support expression indexes and operator classes for PostgreSQL by [default](https://github.com/rails/rails/commit/edc2b7718725016e988089b5fb6d6fb9d6e16882). Add deprecated message to use native resource.

**Comment by ronen** [comment]
Cool -- I'm always happy when AR gets new features obviating the need for schema_plus gems!

There are some syntactic differences which would need to be maintained as part of the deprecation.  But it'd be great to get rid of the custom SQL code in this gem.  

This gem does also provide `case_sensitive: false` as a shortcut for `lower(column)`, that's not currently in AR, so should presumably be maintained.

**Comment by urkle** [comment]
@ronen technically though case_sensitive: false can be done via citext type instead of string/text (support in rails 4.x as well)

**Comment by urkle** [comment]
@ronen who can I contact in @SchemaPlus team to work with in getting all these gems working on. As we are actively using a good amount of these and we are working on upgrading to rails 5.2.   And thus I am more than willing to create the PRs you are wanting to get all of schema plus working fully on rails 5.x.  

We currently utilize  schema+ pg indexes, schema+ foreign keys, schema+ associations, schema+ validations.

**Comment by urkle** [comment]
@ronen that sounds like a plan.

**Comment by ronen** [comment]
@urkle cool.  I sent a collaboration invitation to you last night, hopefully you got it ok...

**Comment by urkle** [comment]
@ronen I sent you an email directly asking about rubygems.org access.. I'll need to push new versions of the schema_dev so I can get tests passing elsewhere.

**Comment by ronen** [comment]
> @ronen I sent you an email directly asking about rubygems.org access

oh man it got flagged as spam!  thanks for the ping.   will continue the conversation by email.

**Comment by urkle** [comment]
This is being implemented in #20
